# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='tea/%Y/%m', verbose_name='图片'),
        ),
    ]
